export const APP_CONSTANTS = {
    IS_CALLING: 'is_calling',
    CALL_ENDED: 'call_ended',
    CALL_ACTIVE: 'call_Active',
    SHOW_KEYPAD: 'show_keypad',
    NUMERIC: 'numeric',
    DEFAULT: 'default',
    DEFAULT_SELECTION: 'DEFAULT_SELECTION',
    UPDATE_DEFAULT: 'UPDATE_DEFAULT',
    ACTIVE: 'ACTIVE',
    EXPIRED: 'EXPIRED',
    CHANGE_NUMBER_MANAGEMENT_TAB:'CHANGE_NUMBER_MANAGEMENT_TAB' ,
    SELECT_NUMBER: 'SELECT_NUMBER',
    UPDATE_LIST_OF_ALL_NUMBERS: 'UPDATE_LIST_OF_ALL_NUMBERS'
};